# Generated by Django 2.2.4 on 2019-08-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20190824_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='external_clientid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
