# Generated by Django 2.2.4 on 2019-08-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_external_clientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientagent',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='clients.Client'),
        ),
    ]
