# Generated by Django 2.2.4 on 2019-08-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParserConfigurationDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('f_format', models.CharField(choices=[('X', 'XLS'), ('C', 'CSV')], max_length=35)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'global parser configuration',
                'verbose_name_plural': 'global parser configurations',
            },
        ),
        migrations.CreateModel(
            name='ColumnPayloadMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=75)),
                ('payload', models.CharField(choices=[('venue', 'Venu'), ('eventdate', 'Event Date'), ('eventtime', 'Event Time'), ('event_name', 'Event Name'), ('section_name', 'Section Name'), ('row_name', 'Row name'), ('seat_num', 'Seat number'), ('last_seat', 'Last seat'), ('num_seats', 'Number seats'), ('acct_id', 'Account ID'), ('barcode', 'Barcode'), ('mobile', 'Mobile')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parser_conf.ParserConfigurationDef')),
            ],
            options={
                'unique_together': {('config', 'payload')},
            },
        ),
    ]
