# Generated by Django 2.2.4 on 2019-08-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_conf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnpayloadmap',
            name='column_name',
            field=models.CharField(max_length=75, verbose_name='expected column'),
        ),
        migrations.AlterField(
            model_name='columnpayloadmap',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='columnpayloadmap',
            name='payload',
            field=models.CharField(choices=[('venue', 'Venu'), ('eventdate', 'Event Date'), ('eventtime', 'Event Time'), ('event_name', 'Event Name'), ('section_name', 'Section Name'), ('row_name', 'Row name'), ('seat_num', 'Seat number'), ('last_seat', 'Last seat'), ('num_seats', 'Number seats'), ('acct_id', 'Account ID'), ('barcode', 'Barcode'), ('mobile', 'Mobile')], max_length=10, verbose_name='map column'),
        ),
        migrations.AlterField(
            model_name='parserconfigurationdef',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='parserconfigurationdef',
            name='f_format',
            field=models.CharField(choices=[('X', 'XLS'), ('C', 'CSV')], default='X', editable=False, max_length=35, verbose_name='supported file'),
        ),
    ]
