# Generated by Django 2.2.4 on 2019-08-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_conf', '0004_auto_20190829_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserconfigurationdef',
            name='brief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parserconfigurationdef',
            name='date_format',
            field=models.CharField(choices=[('%M%d%Y', 'MMDDYY'), ('%d%M%Y', 'DDMMYYY')], default='%d%M%Y', editable=False, max_length=35),
        ),
    ]
