# Generated by Django 2.2.4 on 2019-08-30 02:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_conf', '0005_auto_20190829_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('columns', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleated_at', models.DateTimeField(editable=False, null=True)),
            ],
        ),
    ]
