# Generated by Django 2.2.4 on 2019-08-30 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_conf', '0006_parsercollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserconfigurationdef',
            name='collection',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='parser_conf.ParserCollection'),
        ),
    ]
