# Generated by Django 2.2.4 on 2019-08-30 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_conf', '0007_parserconfigurationdef_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsercollection',
            name='columns',
        ),
    ]
