# Generated by Django 2.2.4 on 2019-08-30 03:04

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_conf', '0008_remove_parsercollection_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsercollection',
            name='columns',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
