# Generated by Django 2.2.4 on 2019-08-30 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_conf', '0009_parsercollection_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsercollection',
            name='brief',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parsercollection',
            name='endpoint',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='columnpayloadmap',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_maps', to='parser_conf.ParserConfigurationDef'),
        ),
        migrations.AlterField(
            model_name='columnpayloadmap',
            name='payload',
            field=models.CharField(max_length=75, verbose_name='map column'),
        ),
        migrations.AlterField(
            model_name='parserconfigurationdef',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parser_conf.ParserCollection'),
        ),
    ]
