# Generated by Django 2.2.4 on 2019-09-06 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_conf', '0011_emailnotification_postingestion_postingestionreport_textnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='parser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_conf.ParserConfigurationDef'),
        ),
        migrations.AddField(
            model_name='postingestionreport',
            name='parser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_conf.ParserConfigurationDef'),
        ),
        migrations.AddField(
            model_name='textnotification',
            name='parser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_conf.ParserConfigurationDef'),
        ),
    ]
