# Generated by Django 2.2.4 on 2019-09-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_conf', '0012_auto_20190906_0423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textnotification',
            old_name='text',
            new_name='mobile',
        ),
    ]
