# Generated by Django 2.2.4 on 2019-09-06 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_conf', '0013_auto_20190906_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='textnotification',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Kindly provide validate mobile number', regex='^\\d{10}$')]),
        ),
    ]
