# Generated by Django 2.2.4 on 2019-09-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_conf', '0016_columnpayloadmap_is_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserCollectionColumm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=75, verbose_name='expected column')),
                ('payload', models.CharField(max_length=75, verbose_name='map column')),
                ('data_type', models.CharField(editable=False, max_length=10, null=True)),
                ('is_required', models.BooleanField(default=False, verbose_name='required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='columnpayloadmap',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='required'),
        ),
    ]
