# Generated by Django 2.2.4 on 2019-09-16 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_conf', '0017_auto_20190916_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsercollectioncolumm',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parser_conf.ParserCollection'),
            preserve_default=False,
        ),
    ]
