# Generated by Django 2.2.4 on 2019-09-16 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_conf', '0018_parsercollectioncolumm_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsercollection',
            name='columns',
        ),
        migrations.AlterField(
            model_name='parsercollectioncolumm',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='parser_conf.ParserCollection'),
        ),
    ]
