# Generated by Django 2.2.4 on 2019-09-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_conf', '0019_auto_20190916_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsercollectioncolumm',
            name='data_type',
            field=models.CharField(choices=[('CharField', 'CharField'), ('IntField', 'IntegerField'), ('TimeField', 'TimeField'), ('DecimalField', 'DecimalField')], max_length=10, null=True),
        ),
    ]
