# Generated by Django 2.2.4 on 2019-08-24 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('body', models.TextField(null=True)),
                ('is_proceed', models.BooleanField(default=True)),
                ('created_t', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.ClientAgent')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionDataAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('f_format', models.CharField(editable=False, max_length=10, null=True)),
                ('is_supported', models.BooleanField(editable=False)),
                ('data_file', models.FileField(upload_to='./ingestion_data/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.IngestionData')),
            ],
        ),
    ]
