# Generated by Django 2.2.4 on 2019-08-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingestiondata',
            old_name='created_t',
            new_name='created_at',
        ),
    ]
