# Generated by Django 2.2.4 on 2019-08-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_ingestiondata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestiondataattachment',
            name='ingestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_files', to='ingestion.IngestionData'),
        ),
        migrations.CreateModel(
            name='IngestionDataTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingestion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_tasks', to='ingestion.IngestionData')),
            ],
        ),
    ]
