# Generated by Django 2.2.4 on 2019-08-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_auto_20190824_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingestiondata',
            old_name='is_proceed',
            new_name='can_process',
        ),
        migrations.AlterField(
            model_name='ingestiondata',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingestiondata',
            name='subject',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
