# Generated by Django 2.2.4 on 2019-08-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_auto_20190825_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestiondata',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingestiondata',
            name='can_process',
            field=models.BooleanField(default=False),
        ),
    ]
