# Generated by Django 2.2.4 on 2019-08-25 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0006_auto_20190825_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestiondatatask',
            name='ingestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_tasks', to='ingestion.IngestionData'),
        ),
    ]
