# Generated by Django 2.2.4 on 2019-08-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0007_auto_20190825_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestiondataattachment',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=125),
        ),
        migrations.AlterField(
            model_name='ingestiondatatask',
            name='status',
            field=models.CharField(choices=[('ack', 'acknowledge'), ('validate_file_format', 'Validate file format task'), ('validate_column_name', 'Validate column names task'), ('validate_column_data', 'Validate column data task'), ('trans_data', 'Transformation data task'), ('prepare_payload_task', 'Prepare payload task'), ('send_payload_task', 'Send payload task'), ('handle_res_task', 'handle response task')], max_length=35),
        ),
    ]
