# Generated by Django 2.2.4 on 2019-08-29 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingestion', '0010_auto_20190825_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingestiondatatask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='ingestiondata',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingestiondata',
            name='status',
            field=models.CharField(choices=[('N', 'NEW'), ('S', 'Stopped'), ('C_F', 'Failed'), ('C_S', 'Completed')], default='N', max_length=5),
        ),
        migrations.AlterField(
            model_name='ingestiondatatask',
            name='status',
            field=models.CharField(choices=[('N', 'NEW'), ('S', 'Stopped'), ('C_F', 'Failed'), ('C_S', 'Completed')], max_length=35),
        ),
        migrations.AlterField(
            model_name='ingestiondatatask',
            name='task',
            field=models.CharField(choices=[('ack', 'acknowledge'), ('ack_stoped', 'Acknowledge! can not proceed further'), ('validate_file_format', 'Validate file format task'), ('validate_column_name', 'Validate column names task'), ('validate_column_data', 'Validate column data task'), ('trans_data', 'Transformation data task'), ('prepare_payload_task', 'Prepare payload task'), ('send_payload_task', 'Send payload task'), ('handle_res_task', 'Handle response task')], max_length=35),
        ),
    ]
