# Generated by Django 2.2.4 on 2019-08-30 07:43

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0013_auto_20190830_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='N', max_length=2)),
                ('inventory', django.contrib.postgres.fields.hstore.HStoreField()),
                ('batch_id', models.CharField(max_length=35, null=True)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('processed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_inventories', to='ingestion.IngestionData')),
            ],
        ),
    ]
