# Generated by Django 2.2.4 on 2019-08-30 09:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0014_ingestioninventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestiondataattachment',
            name='headers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), null=True, size=None),
        ),
    ]
