# Generated by Django 2.2.4 on 2019-09-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0016_ingestiondata_parser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestiondata',
            name='einfo',
            field=models.TextField(editable=False, null=True),
        ),
    ]
