# Generated by Django 2.2.4 on 2019-09-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0017_ingestiondata_einfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingestioninventory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='ingestiondatatask',
            name='task',
            field=models.CharField(choices=[('ack', 'acknowledge'), ('ack_stoped', 'Acknowledge! can not proceed further'), ('validate_file_format', 'Validate file format task'), ('validate_column_name', 'Validate column names task'), ('ingestion_task', 'Ingestion tasks '), ('validate_column_data', 'Validate column data task'), ('trans_data', 'Transformation data task'), ('prepare_payload_task', 'Prepare payload task'), ('send_payload_task', 'Send payload task'), ('handle_res_task', 'Handle response task')], max_length=35),
        ),
    ]
