# Generated by Django 2.2.4 on 2019-09-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0018_auto_20190906_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestioninventory',
            name='status_code',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
