# Generated by Django 2.2.4 on 2019-09-19 05:04

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0019_ingestioninventory_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestiondata',
            name='event_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ingestiondata',
            name='event_meta',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
