# Generated by Django 2.2.4 on 2019-09-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0020_auto_20190919_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestiondata',
            name='ing_type',
            field=models.CharField(choices=[('E', 'Email'), ('W', 'Web'), ('A', 'API')], editable=False, max_length=2, null=True),
        ),
    ]
